### ISSUE TITLE
[FEATURE] Post Cell 기획 변경으로 인한 UI변경

### ISSUE THREAD

**Issue by leegyoungmin** [Young-Child/FanFollow#103]
### Description
- POST Cell 기획의 변경으로 인한 셀 디자인 변경

### ToDo
- [x]  Post Cell 내부 이미지 스크롤 뷰 개별 뷰로 변경
- [x]  Post Cell 내부 링크 보여주는 뷰 변경
    - [x]  Post Cell 내부 링크 네비게이션 설정

### ETC
기타사항, 추가사항에 대해서 작성하세요.
