### ISSUE TITLE
[FEATURE] 사용자 신고, 게시물 신고 Data 정의 및 UI 구현

### ISSUE THREAD

**Issue by KyoPak** [Young-Child/FanFollow#145]
### Description
사용자 신고, 게시물 신고 Data 정의 및 TableView Cell 구현

### ToDo
- [x]  ReportViewController, ReportViewModel 구현
- [x]  SendReportUseCase로 통합
- [x]  ReportRepository 부분 수정
- [x]  ReportType, ReportReason 데이터 타입 구현
- [x]  ReportReasonTableViewCell 구현

### ETC
기타사항, 추가사항에 대해서 작성하세요.
