### ISSUE TITLE
feat: 채팅방 관련된 서비스 타입 구현

### ISSUE THREAD

**Issue by leegyoungmin** [Young-Child/FanFollow#18]
### Description
채팅방에 대한 데이터를 불러오는 서비스를 구현합니다.

### ToDo
- [x] 서비스 프로토콜 생성
- [x] 채팅방 URLRequestDirector 생성
- [x] 채팅방 읽는 메서드
- [x] 채팅방 나가기 기능
- [x] 채팅방 생성 기능
- [x] 채팅방 삭제 기능

### ETC
채팅방과 관련된 것은 이곳에서 수행하고, 채팅 메시지와 관련된 부분은 라이브러리를 사용해서 WebSocket으로 구현하려고 합니다.
