### ISSUE TITLE
[TEST] Default Chat Service Test 코드 작성

### ISSUE THREAD

**Issue by leegyoungmin** [Young-Child/FanFollow#27]
### Description
Chat 서비스에 대한 테스트 코드 작성

### Edge Case (추후 추가 예정)
- [x] 정상적인 사용자 ID를 전달하였을 때 정상적인 채팅방 리스트를 가지고 오는가에 대한 테스트
- [x] 비정상적인 사용자 ID를 전달하였을 때 에러를 방출하는지에 대한 테스트
- [x] 정상적인 사용자 ID를 전달하였을 때 새로운 채팅방 생성 이벤트가 성공인지에 대한 테스트
- [x] 비정상적인 사용자 ID를 전달하였을 때 새로운 채팅방 생성 이벤트가 에러를 반환하는 지에 대한 테스트
- [x] 정상적인 데이터를 통해서 채팅방 떠나기 메서드가 next 이벤트를 방출하는지에 대한 테스트
- [x] 비정상적인 데이터를 통해서 채팅방 떠나기 메서드가 error 이벤트를 방출하는지에 대한 테스트
- [x] 정상적인 데이터를 통해서 채팅방 삭제 메서드가 완료 이벤트를 방출하는지에 대한 테스트
- [x] 비정상적인 데이터를 통해서 채팅방 삭제 메서드가 에러 이벤트를 방출하는지에 대한 테스트

### ToDo
- [x] Mock 데이터 생성
- [x] Default Chat Service에 대한 테스트 케이스 생성
- [x] 테스트 코드 작성
