### ISSUE TITLE
[TEST] 네트워크 매니저 테스트 작성

### ISSUE THREAD

**Issue by leegyoungmin** [Young-Child/FanFollow#28]
### Description
`Stub`한 네트워크 매니저 타입을 구현하고, 이에 대한 테스트를 진행합니다.
- 네트워크가 제공되지 않는 상황에서 테스트를 구현할 수 있습니다.

### Edge Case
- [x] 정상적인 값을 전달 할 수 있는지
- [x] 에러가 발생하였을 때 정상적으로 에러를 방출하지

### ToDo
- [x] NetworkManager 테스트케이스 맞춰서 구현
- [x] StubURLSession 타입 구현
- [x] MockURLSessionDataTask 타입 구현

### ETC
- 서비스 타입을 테스트하기 위해서는 해당 StubNetworkManager를 활용
