### ISSUE TITLE
[TEST] FollowService, UserInformationService 테스트 작성

### ISSUE THREAD

**Issue by junho15** [Young-Child/FanFollow#32]
### Description
FollowService, UserInformationService 테스트 작성

### Edge Case
- [x] 정상적인 값일 때 확인
- [x] 에러일 때 확인

### ToDo
- [x] FollowService 테스트 작성
- [x] UserInformationService 테스트 작성

### ETC
StubNetworkManger 필요
