### ISSUE TITLE
[TEST] LikeService 테스트 코드 작성

### ISSUE THREAD

**Issue by KyoPak** [Young-Child/FanFollow#39]
### Description
LikeService 테스트 코드 작성

### Edge Case
- [x] 각 메서드에 대한 반환값 확인 

### ToDo
- [x] fetchPostLikeCount() 테스트 작성
- [x] createPostLike() 테스트 작성
- [x] deletePostLike() 테스트 작성
