### ISSUE TITLE
[FEATURE] User, Creator, Fan Model 생성 

### ISSUE THREAD

**Issue by KyoPak** [Young-Child/FanFollow#55]
### Description
User, Creator, Fan Model 생성 

### ToDo
- [x] User 타입 생성
- [x] Creator 타입 생성
- [x] Fan 타입 생성 

### ETC
기타사항, 추가사항에 대해서 작성하세요.
