### ISSUE TITLE
[TEST] UseCase(FetchFeedUseCase 외) 테스트 작성

### ISSUE THREAD

**Issue by junho15** [Young-Child/FanFollow#63]
### Description
 FetchFeedUseCase, ChangeLikeUseCase, FetchCreatorInformationUseCase, FetchUserInformationUseCase, FetchCreatorPostsUseCase 테스트 작성

### Edge Case
- [X] 정상적인 값일 때 확인
- [X] 에러일 때 확인

### ToDo
- [x] FetchFeedUseCase 테스트 작성
- [x] ChangeLikeUseCase 테스트 작성
- [x] FetchCreatorInformationUseCase 테스트 작성
- [x] FetchUserInformationUseCase 테스트 작성
- [x] FetchCreatorPostsUseCase 테스트 작성

### ETC
필요한 StubRepository 구현
